# Generated by Django 5.1.1 on 2024-09-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='globalproject/imgs/usr.jpeg', null=True, upload_to='posts/'),
        ),
    ]
